### ISSUE TITLE
build 5.4 in ubuntu 14.04 faild

### ISSUE THREAD

**Issue by mrzeta** [kalgecin/CACHeCoin#2]
when i build 5.4 in the ubuntu 14.04 show this error- - !
g++ -O2 -msse2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter  -DBOOST_SPIRIT_THREADSAFE -I/home/CACHeCoin/src -I/home/CACHeCoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -DSCRYPT_KECCAK512 -DSCRYPT_CHACHA -DSCRYPT_CHOOSE_COMPILETIME -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -o cachecoind obj/alert.o obj/version.o obj/checkpoints.o obj/netbase.o obj/addrman.o obj/crypter.o obj/key.o obj/db.o obj/init.o obj/irc.o obj/keystore.o obj/main.o obj/net.o obj/protocol.o obj/bitcoinrpc.o obj/rpcdump.o obj/rpcnet.o obj/rpcmining.o obj/rpcwallet.o obj/rpcblockchain.o obj/rpcrawtransaction.o obj/script.o obj/sync.o obj/util.o obj/wallet.o obj/walletdb.o obj/noui.o obj/kernel.o obj/pbkdf2.o obj/scrypt_mine.o obj/scrypt-x86.o obj/scrypt-x86_64.o obj/scrypt-jane.o -Wl,-z,relro -Wl,-z,now   -Wl,-Bdynamic -l boost_system -l boost_filesystem -l boost_program_options -l boost_thread -l db_cxx -l ssl -l crypto -l miniupnpc -Wl,-Bdynamic -l z -l dl -l pthread
obj/walletdb.o: In function `BackupWallet(CWallet const&, std::string const&)':
walletdb.cpp:(.text+0x283d): undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
make: *** [cachecoind] Error 1

what happend - -! 5.3 is fine!!

**Comment by kalgecin** [comment]
https://github.com/kalgecin/CACHeCoin/blob/master/README

`sudo apt-get install git build-essential libboost-all-dev libdb++-dev libminiupnpc-dev libcurl4-openssl-dev`

at the bottom, there's build instructions for ubuntu. and the file you are getting error from hasn't been modified since initial commit. so you are getting the error due to changes on your end
